/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef BITRATE_H
#define BITRATE_H

/* function declarations */
void init_bitrate(void);
Netsnmp_Node_Handler handle_bitrate;

#endif /* BITRATE_H */
