/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef DPID_H
#define DPID_H

/* function declarations */
void init_dpid(void);
Netsnmp_Node_Handler handle_dpid;

#endif /* DPID_H */
