/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef ESSID_H
#define ESSID_H

/* function declarations */
void init_essid(void);
Netsnmp_Node_Handler handle_essid;

#endif /* ESSID_H */
