/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef TXPOWER_H
#define TXPOWER_H

/* function declarations */
void init_txpower(void);
Netsnmp_Node_Handler handle_txpower;

#endif /* TXPOWER_H */
