/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef WIFINOTIF_H
#define WIFINOTIF_H

/* function declarations */
int send_wifiNotif_trap(void);
void init_wifiNotif(void);

#endif /* WIFINOTIF_H */
