/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef KEEPALIVENOTIF_H
#define KEEPALIVENOTIF_H

#define KEEPALIVE_INTERVAL 30

/* function declarations */
void send_keepAliveNotif_trap(unsigned int, void*);
void init_keepAliveNotif(void);

#endif /* KEEPALIVENOTIF_H */
