/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "keepAliveNotif.h"
#include "util.h"

/**************************** OF INCLUDES **************************/

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <inttypes.h>
#include <unistd.h>
#include <signal.h>

#include "vconn.h"
#include "ofpbuf.h"
#include "openflow/openflow.h"
#include "xtoxll.h"

#define SNMP_TRAP_HOST "openflow2.stanford.edu"

void
send_keepAliveNotif_trap(unsigned int clientreg, void *clientarg)
{

        char dpid_str[128];
        struct ofpbuf *request;
        struct vconn *vconn;
        struct ofpbuf *reply;
        struct ofp_switch_features *osf;
        struct ofp_phy_port *opp;
        uint16_t size;
        int i;
        int pid;

        time_init();
        make_openflow(sizeof(struct ofp_header),OFPT_FEATURES_REQUEST , &request);
        update_openflow_length(request);
        vconn_open_block("nl:0", OFP_VERSION, &vconn);
        vconn_transact(vconn, request, &reply);
        vconn_close(vconn);

        osf = (struct ofp_switch_features*) reply->data;
        sprintf(dpid_str, "%"PRIx64"", ntohll(osf->datapath_id));


        netsnmp_variable_list  *var_list = NULL;
        oid snmptrap_oid[] = {1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0};
        oid keepAliveNotif_oid[] = { 1,3,6,1,3,108,0,10 };
        oid dpid_oid[] = { 1,3,6,1,3,108,0,5, 0 };

        /*
         * Set the snmpTrapOid.0 value
         */
        snmp_varlist_add_variable(&var_list,
                        snmptrap_oid, OID_LENGTH(snmptrap_oid),
                        ASN_OBJECT_ID,
                        (u_char*)keepAliveNotif_oid, sizeof(keepAliveNotif_oid));

        /*
         * Add any objects from the trap definition
         */
        snmp_varlist_add_variable(&var_list,
                        dpid_oid, OID_LENGTH(dpid_oid),
                        ASN_OCTET_STR, dpid_str, strlen(dpid_str));

        /*
         * Send the trap to the list of configured destinations
         *  and clean up
         */
        //send_v2trap( var_list );
        if(signal(SIGCHLD, SIG_IGN))
                perror("signal(SIGCHLD, SIG_IGN)");
        pid = fork();
        if(pid == 0) {
                execl("/usr/local/bin/snmptrap", "/usr/local/bin/snmptrap", "-v2c", "-c", "public", SNMP_TRAP_HOST, "\"\"", "POMI-MOBILITY-MIB::keepAliveNotif", "POMI-MOBILITY-MIB::dpid.0", "s", dpid_str, (char*)0);
                exit(0);
        }
        printf("Sent keep-alive trap\n");
        snmp_free_varbind( var_list );

        //return SNMP_ERR_NOERROR;
}

void init_keepAliveNotif(void)
{
    DEBUGMSGTL(("keep-alive notification", "initializing the notification subagent\n"));
    send_keepAliveNotif_trap(0, NULL); // the arguments are dummy
    snmp_alarm_register(KEEPALIVE_INTERVAL, SA_REPEAT, send_keepAliveNotif_trap, NULL);
}
