/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "wifiMac.h"
#include "util.h"

#include <unistd.h>
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <getopt.h>
#include <pthread.h>
#include <netdb.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/if.h>
#include <net/if_arp.h>
#include <linux/if_ether.h>
#include <linux/if_bonding.h>
#include <linux/sockios.h>
#include <linux/ethtool.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <inttypes.h>

/** Initializes the wifiMac module */
void
init_wifiMac(void)
{
    static oid wifiMac_oid[] = { 1,3,6,1,3,108,0,7 };

  DEBUGMSGTL(("wifiMac", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("wifiMac", handle_wifiMac,
                               wifiMac_oid, OID_LENGTH(wifiMac_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_wifiMac(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
        /* Open a basic socket */
        int skfd = -1;
        if ((skfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
                printf("Failed to open socket\n");
                return -1;
        }

        /* Get MAC address 
         * hexmac: stores the mac address at the end of this block
         */
        struct ifreq mac_ifr;
        mac_ifr.ifr_data = (void *) malloc(sizeof(struct ifslave));
        strcpy(mac_ifr.ifr_name, INTERFACE);

        int ret;
        uint64_t mac_net, mac_host;
        char mac_str[13];
        if ((ret = ioctl(skfd, SIOCGIFHWADDR, &mac_ifr)) < 0) {
                printf("GetHWAdr ioctl call failed : %d\n", ret);
                return -1;
        }
        memcpy(&mac_net, mac_ifr.ifr_hwaddr.sa_data, 6);
        mac_host = ntohl(mac_net);
        mac_host = (mac_host << 32) + ntohl(mac_net >> 32);
        sprintf(mac_str, "%llx", (long long int)mac_host);

    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
                printf("wifiMac MODE_GET\n");
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) mac_str, strlen(mac_str));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_wifiMac\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

                printf("wifiMac - return\n");
    return SNMP_ERR_NOERROR;
}
