#! /bin/sh
### BEGIN INIT INFO
# Provides:          openroads
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenRoads Services
# Description:       This file starts/stops snmp services for OpenRoads.
### END INIT INFO

# Author: ykk <yapkke@stanford.edu>
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="OpenRoads"
NAME=openroads
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
for cmd in wifi trap keepalive
do
        if [ -x "/etc/snmp/${cmd}_subagent" ] 
        then
                :
        else 
                echo "$cmd subagent missing"
                exit 0
        fi
done

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
        echo "Starts SNMP subagents"
        /etc/snmp/keepalive_subagent -x /var/agentx/master
        /etc/snmp/trap_subagent -x /var/agentx/master
        /etc/snmp/wifi_subagent -x /var/agentx/master
	return 0
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
        echo "Stops SNMP subagents"
	killall keepalive_subagent
        killall wifi_subagent
	killall trap_subagent
	return 0
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
        do_stop
	do_start
}

case "$1" in
  start)
        do_start
	;;
  stop)
	do_stop
	;;
  restart)
       do_reload
       ;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
